<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld/pb/helloworld.proto

namespace GPBMetadata\Helloworld\Pb;

class Helloworld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa4010a1e68656c6c6f776f726c642f70622f68656c6c6f776f726c642e" .
            "70726f746f12027062221c0a0c48656c6c6f52657175657374120c0a046e" .
            "616d65180120012809221d0a0a48656c6c6f5265706c79120f0a076d6573" .
            "7361676518012001280932390a0747726565746572122e0a085361794865" .
            "6c6c6f12102e70622e48656c6c6f526571756573741a0e2e70622e48656c" .
            "6c6f5265706c792200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

