// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.10.1
// source: proto/cart/cart_types.proto

package cart

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// 来源
type SourcePlatform int32

const (
	SourcePlatform_PLUM SourcePlatform = 0 // 红布林APP
	SourcePlatform_LIVE SourcePlatform = 1 // 直播APP
)

// Enum value maps for SourcePlatform.
var (
	SourcePlatform_name = map[int32]string{
		0: "PLUM",
		1: "LIVE",
	}
	SourcePlatform_value = map[string]int32{
		"PLUM": 0,
		"LIVE": 1,
	}
)

func (x SourcePlatform) Enum() *SourcePlatform {
	p := new(SourcePlatform)
	*p = x
	return p
}

func (x SourcePlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourcePlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_cart_cart_types_proto_enumTypes[0].Descriptor()
}

func (SourcePlatform) Type() protoreflect.EnumType {
	return &file_proto_cart_cart_types_proto_enumTypes[0]
}

func (x SourcePlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourcePlatform.Descriptor instead.
func (SourcePlatform) EnumDescriptor() ([]byte, []int) {
	return file_proto_cart_cart_types_proto_rawDescGZIP(), []int{0}
}

var File_proto_cart_cart_types_proto protoreflect.FileDescriptor

var file_proto_cart_cart_types_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x72, 0x74, 0x2f, 0x63, 0x61, 0x72,
	0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63,
	0x61, 0x72, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2a, 0x24, 0x0a, 0x0e, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x12, 0x08, 0x0a, 0x04, 0x50,
	0x4c, 0x55, 0x4d, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x49, 0x56, 0x45, 0x10, 0x01, 0x42,
	0x28, 0x5a, 0x0a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x72, 0x74, 0xca, 0x02, 0x19,
	0x61, 0x70, 0x70, 0x5c, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x6e, 0x65, 0x6e, 0x74, 0x73, 0x5c, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x5c, 0x63, 0x61, 0x72, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_cart_cart_types_proto_rawDescOnce sync.Once
	file_proto_cart_cart_types_proto_rawDescData = file_proto_cart_cart_types_proto_rawDesc
)

func file_proto_cart_cart_types_proto_rawDescGZIP() []byte {
	file_proto_cart_cart_types_proto_rawDescOnce.Do(func() {
		file_proto_cart_cart_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_cart_cart_types_proto_rawDescData)
	})
	return file_proto_cart_cart_types_proto_rawDescData
}

var file_proto_cart_cart_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_cart_cart_types_proto_goTypes = []interface{}{
	(SourcePlatform)(0), // 0: cart_types.sourcePlatform
}
var file_proto_cart_cart_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_cart_cart_types_proto_init() }
func file_proto_cart_cart_types_proto_init() {
	if File_proto_cart_cart_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_cart_cart_types_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_cart_cart_types_proto_goTypes,
		DependencyIndexes: file_proto_cart_cart_types_proto_depIdxs,
		EnumInfos:         file_proto_cart_cart_types_proto_enumTypes,
	}.Build()
	File_proto_cart_cart_types_proto = out.File
	file_proto_cart_cart_types_proto_rawDesc = nil
	file_proto_cart_cart_types_proto_goTypes = nil
	file_proto_cart_cart_types_proto_depIdxs = nil
}
