server:
  address: "0.0.0.0:8091"
  name: "cart-srv-test"

consul:
  address: "dev03.aplum-inc.com:8500"

aplumDB:
  user: aplum
  password: plum2016
  host: 127.0.0.1
  port: 3306
  db: aplum
  charset: utf8
  parsetime: "true"
  loc: Local
  timeout: 15s
  readTimeout: 10s
  writeTimeout: 10s
