log:
  level: "info"
  dev: true

server:
  read_timeout: 60
  write_timeout: 60
  http_addr: ":8080"
  mode: release
  pprof: true

aplum_db:
  host: "10.26.50.132"
  user: "aplum"
  password: "plum2016"
  port: "3306"
  db: "aplum"
  max_idle_conns: 10
  max_open_conns: 10
  log: false

redis:
  host: "127.0.0.1:6379"
  password: ''
  db: 3
  pool_size: 10
  min_idle_conns: 5

short_url:
  base_url: "http://127.0.0.1:8080"
