server:
  read_timeout: 60
  write_timeout: 60
  http_addr: ":8080"
  mode: release
  pprof: true

log:
  filename: "logs/shop.log"
  max_size: 10
  max_backups: 2

redis:
  host: "localhost:6379"
  password: ""
  db: 1